name: Reusable workflow

on:
  workflow_call:
    inputs:
      publish-aws:
        required: true
        type: boolean
    secrets:
      aws-key:
        required: true
      aws-a-key:
        required: true

jobs:
  pytests:
    name: Python Test
    env:
      TESTS_RESULT_DIR: ${{ github.workspace }}/testResults
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: read
        checks: write
        pull-requests: write
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout Tests
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest-playwright
        pip install pytest-reporter-html1
        pip install pytest-xdist
        python -m pip install playwright
    - name: Install playwright browsers
      run: | 
        python -m playwright install
        npx playwright install-deps
    - name: "Print out Workspace"
      run: ls ${{ github.workspace }}
    - name: "Print out passed vars"
      run: echo ${{ toJSON(inputs.publish-aws) }}
    - name: Run Tests
      run: pytest ${{ github.workspace }} -m regression --junitxml=${{ env.TESTS_RESULT_DIR }}/junit_results.xml --report=${{ env.TESTS_RESULT_DIR }}/python_tests_result_report.html --template=html1/index.html -n auto
    - name: Publish Tests Results
      uses: EnricoMi/publish-unit-test-result-action@v2.7.0 
      with:
        check_name: Python Test Results
        files: |
          ${{ env.TESTS_RESULT_DIR }}/*.xml
    - name: Setting AWS credentials
      if: ${{ inputs.publish-aws == 'true' }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.aws-key}}
        aws-secret-access-key: ${{secrets.aws-a-key}}
        aws-region: eu-central-1
    - name: Publish Python Results to S3
      run: aws s3 sync ${{ env.TESTS_RESULT_DIR }}/ s3://awoha.xyz
