name: Reusable workflow

on:
  workflow_call:
    inputs:
      check-out-path:
        required: true
        type: string
      publish-aws:
        required: true
        type: boolean
    secrets:
      aws-bucket-region:
        required: true
      aws-bucket:
        required: true
      aws-key:
        required: true
      aws-a-key:
        required: true

jobs:
  pytests:
    name: Python Test
    env:
      #github.workspace
      tests_result_dir: ${{ inputs.check-out-path }}/testResults
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: read
        checks: write
        pull-requests: write
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout Tests
      uses: actions/checkout@v2
      with:
        repository: AbyssalWhale/python-pw
        path: ${{ inputs.check-out-path }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest-playwright
        pip install pytest-reporter-html1
        pip install pytest-xdist
        python -m pip install playwright
    - name: Install playwright browsers
      run: | 
        python -m playwright install
        npx playwright install-deps
    - name: "Print out vars"
      run: |
        echo "Publish to AWS: ${{ toJSON(inputs.publish-aws) }}"
        echo "Check out path: ${{ toJSON(inputs.check-out-path) }}"
        echo "-Check out content-"
        ls ${{ inputs.check-out-path }}
    - name: Run Tests
      run: pytest ${{ inputs.check-out-path }} -m regression --junitxml=${{ env.tests_result_dir }}/junit_results.xml --report=${{ env.tests_result_dir }}/python_tests_result_report.html --template=html1/index.html -n auto
    - name: Publish Tests Results
      uses: EnricoMi/publish-unit-test-result-action@v2.7.0 
      with:
        check_name: Python Test Results
        files: |
          ${{ env.tests_result_dir }}/*.xml
    - name: Setting AWS credentials
      if: ${{ inputs.publish-aws == 'true' }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.aws-key}}
        aws-secret-access-key: ${{secrets.aws-a-key}}
        aws-region: ${{secrets.aws-bucket-region}}
    - name: Publish Python Results to S3
      if: ${{ inputs.publish-aws == 'true' }}
      run: aws s3 sync ${{ env.tests_result_dir }}/ ${{secrets.aws-bucket}}
